### ISSUE TITLE
Port 80 is not available on Windows

### ISSUE THREAD

**Issue by zachariahyoung** [csantanapr/knative-kind#10]
Any suggestion on getting pass the following port issue?  I'm running on Windows 10.

KinD version is kind v0.10.0 go1.15.7 windows/amd64
Creating cluster "knative" ...
 • Ensuring node image (kindest/node:v1.20.2) �  ...
 ✓ Ensuring node image (kindest/node:v1.20.2) �
 • Preparing nodes �   ...
 ✗ Preparing nodes �
ERROR: failed to create cluster: docker run error: command "docker run --hostname knative-control-plane --name knative-control-plane --label io.x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.x-k8s.kind.cluster=knative --net kind --restart=on-failure:1 --publish=0.0.0.0:80:31080/TCP --publish=127.0.0.1:50865:6443/TCP kindest/node:v1.20.2@sha256:8f7ea6e7642c0da54f04a7ee10431549c0257315b3a634f6ef2fecaaedb19bab" failed with error: exit status 125

Command Output: 58bba70d289885b015187855f6b3bfbb107b746946a9dbcf5825d85250eb8e54
docker: Error response from daemon: Ports are not available: listen tcp 0.0.0.0:80: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by csantanapr** [comment]
I don't have windows to test this on.

But I'm guessing that port 80 is not allowed since is a privilege port.

You could try asking in channel kind in kubernetes Slack to see if there are any windows users that could help answer how to get port `80` to work on windows host. so you can have a nice URL `http://hello.default.127.0.0.1.nip.io` 

This is the kind config I use you can paste in slack
```
cat <<EOF | kind create cluster --name knative --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:1.20.2@sha256:8f7ea6e7642c0da54f04a7ee10431549c0257315b3a634f6ef2fecaaedb19bab
  extraPortMappings:
  - containerPort: 31080 # expose port 31380 of the node to port 80 on the host, later to be use by kourier ingress
    hostPort: 80
EOF
```

you can also put the same info in a git issue in kind git repository as a question
