### ISSUE TITLE
Doesn't work on GitHub actions

### ISSUE THREAD

**Issue by boramalper** [csantanapr/knative-kind#47]
I have considered using your repo to setup Knative on KinD for testing my code on GitHub-hosted runners, but the setup hangs at setting up Knative Eventing for some unknown reason.

My GitHub Actions manifest (simplified):

```yaml
name: My Action

defaults:
  run:
    shell: bash

jobs:
  my-job:
    name: My job
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      
      - name: Install KinD
        run: |
          set -x

          curl -sL get.konk.dev | bash

      - # ...
```
